OpenVPNApp/urls.py
from django.urls import path

from . import views

app_name = "OpenVPNApp"

urlpatterns = [
    path(r"", views.index, name="index"),
    path("restart", views.restart, name="restart"),
    path("downloadConfigFile", views.download_config_file, name="downloadConfigFile"),
    path("changePort", views.change_port, name="changePort"),
    path("downloadClientWin", views.download_client_win, name="downloadClientWin"),
    path("downloadClientMac", views.download_client_mac, name="downloadClientMac"),
]

OpenvpnManage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('openvpn/', include('OpenVPNApp.urls')),
    path('admin/', admin.site.urls),
    path('wechat/', include('WXPublic.urls')),
]

WXPublic/urls.py
from django.urls import path, re_path

from . import views

app_name = "OpenVPNApp"

urlpatterns = [
    path('wx', views.wx, name='wx'),
    re_path('wx?P<signature>&?P<echostr>&?P<timestamp>&?P<nonce>', views.wx, name='wx'),
    path('gettoken', views.get_token, name='gettoken'),
    path('test', views.test, name='test'),
]

# urlpatterns = [
#     re_path(r'articles(?P<year>[0-9]{4})/$', views.wx),
#     # re_path(r'^articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.month_archive),
#     # re_path(r'^articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<slug>[\w-]+)/$', views.article_detail),
# ]

OpenVPNApp/views.py
# coding=utf-8
# 这是一个小小的里程碑，
# 因为我已经解决了关闭服务-更换端口-修改配置文件-重启服务的完整流程

from django.shortcuts import render

from django.core.files import File

from django.http import HttpResponse, FileResponse

from django.shortcuts import redirect

from django.template import loader

import os

import threading


# Create your views here.

def index(request):
    template = loader.get_template(r"OpenVPNApp/index.html")
    with open(r"setting.json", "r", encoding="UTF-8") as f:
        content = f.readlines()
        config_file = eval("".join(content))
    context = {
        "port": str(config_file["port"]),
        "message": ""
    }
    if request.META.get('HTTP_X_FORWARDED_FOR'):
        ip = request.META.get("HTTP_X_FORWARDED_FOR")
    else:
        ip = request.META.get("REMOTE_ADDR")

    print("ip : ", ip)
    return HttpResponse(template.render(context, request))

def restart(request):
    print("重启服务")
    '''
    重启openvpn服务
    '''
    os.system(r'/etc/openvpn/killopenvpn.sh')
    start_openvpn_thread = threading.Thread(target=start_openvpn_fun)
    start_openvpn_thread.start()
    response = redirect("/openvpn/")
    return response
    # template = loader.get_template(r"OpenVPNApp/index.html")
    # with open(r"setting.json", "r", encoding="UTF-8") as f:
    #     content = f.readlines()
    #     config_file = eval("".join(content))
    # context = {
    #     "port": str(config_file["port"])
    # }
    # return HttpResponse(template.render(context, request))

def download_config_file(request):
    print("下载配置文件")
    filepath=(r"media/client.ovpn")
    f = open(filepath, "rb")
    response = FileResponse(f)
    f.close
    response["content_type"] = "application/octet-stream"
    response["Content-Disposition"] = "attachment; filename=" + os.path.basename(filepath)
    return response

def download_client_win(request):
    print("下载客户端")
    filepath=(r"media/OpenVPN-2.5.5-I602-amd64.msi")
    # filepath=(r"D:\OpenVPNManage\OpenvpnManage\media\OpenVPN-2.5.5-I602-amd64.msi")
    f = open(filepath, "rb")
    response = FileResponse(f)
    f.close
    response["content_type"] = "application/octet-stream"
    response["Content-Disposition"] = "attachment; filename=" + os.path.basename(filepath)
    return response

def download_client_mac(request):
    print("下载客户端")
    filepath=(r"media/openvpn-connect-3.3.6.4368_signed.dmg")
    # filepath=(r"D:\OpenVPNManage\OpenvpnManage\media\openvpn-connect-3.3.6.4368_signed.dmg")
    f = open(filepath, "rb")
    response = FileResponse(f)
    f.close
    response["content_type"] = "application/octet-stream"
    response["Content-Disposition"] = "attachment; filename=" + os.path.basename(filepath)
    return response

def start_openvpn_fun():
    # 运行linux重启服务的脚本
    os.system(r'/etc/openvpn/startopenvpn.sh')

def change_port(request):
    print("修改服务端配置文件的运行端口")
    create_server_config_file()
    print("重启服务")
    os.system(r'/etc/openvpn/killopenvpn.sh')
    start_openvpn_thread = threading.Thread(target=start_openvpn_fun)
    start_openvpn_thread.start()
    print("修改客户端配置文件")
    create_client_config_file()
    print("开启防火墙")
    response = redirect("/openvpn/")
    return response


config_file_content = []


import json

def create_client_config_file():
    
    config_file = {
    }

    with open(r"setting.json", "r", encoding="UTF-8") as f:
        content = f.readlines()
        config_file = eval("".join(content))
    with open(r"media/client-one.ovpn", "r", encoding="UTF-8") as f:
        config_file_content = f.readlines()
        config_file_content.append("remote " + config_file["ip"] + " " + str(config_file["port"]))
    with open(r"media/client.ovpn", "w", encoding="UTF-8") as f:
        f.write("".join(config_file_content))
    
def create_server_config_file(port=None):
    
    config_file = {
    }

    with open(r"setting.json", "r", encoding="UTF-8") as f:
        content = f.readlines()
        config_file = eval("".join(content))
        
    if port == None:
        config_file["port"] = config_file["port"] + 1
    else:
        config_file["port"] = port
        
    with open(r"media/server-one.conf", "r", encoding="UTF-8") as f:
        config_file_content = f.readlines()
        config_file_content.append("port "+ str(config_file["port"]))
    with open(r"/etc/openvpn/server_auto.conf", "w", encoding="UTF-8") as f:
        f.write("".join(config_file_content))
        
    with open(r"setting.json", "w", encoding="UTF-8") as f:
        f.write(json.dumps(config_file))
        
    os.system("ufw allow " + str(config_file["port"]))


if __name__ == "__main__":
    # 这是测试代码
    print("测试中")
    create_server_config_file()
    create_client_config_file()

OpenVPNApp/templates/OpenVPNApp/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>我的站点</title>
</head>
<body>
    <h1>管理我的站点</h1>
    <br></br>
    <p>当前VPN端口为：{{ port }}</p>
    <a href={% url "OpenVPNApp:restart" %}>重启服务</a>
    <br></br>
    <a href={% url "OpenVPNApp:changePort" %}>修改端口</a>
    <br></br>
    <a href={% url "OpenVPNApp:downloadConfigFile" %}>下载最新配置文件</a>
    <br></br>
    <a href={% url "OpenVPNApp:downloadClientWin" %}>下载win客户端</a>
    <br></br>
    <a href={% url "OpenVPNApp:downloadClientMac" %}>下载mac客户端</a>
    <p>{{ message }}</p>
    <br></br>
    <h3>使用方法</h3>
    <li>点击下载win客户端。并按照软件指引安装</li>
    <li>点击下载最新配置文件。</li>
    <li>点击下载完成的配置文件导入openvpn。</li>
    <li>右下角找到OpenVPN GUI应用，右键选择连接即可</li>
    <h3>注意事项</h3>
    <p>vpn端口一般一到两天会更新一次，如果无法连接上服务器，请先确认自己的客户端配置文件的端口是否正确！</p>
    <p>确认端口正确以后依然无法连接上vpn，可以点击修改端口按钮，将客户端配置文件修改为最新端口后连接vpn</p>
    <p>重启服务和修改端口需要一定时间，建议重启服务和修改端口后5分钟再尝试连接vpn</p>
    <p>请不要重复点击修改端口按钮！如果修改端口两次后依然无法连接vpn，大概率是服务器内部发生错误，请不要再尝试了，如果你认识作者，可联系作者排查故障。</p>
    <p>本服务仅提供给朋友学习交流之用，请勿使用本服务进行违法犯罪！</p>
    <br></br>
    {% comment %} <p>应该要出一个客户端使用教程，但是做网页实在是太菜了，不过搜索OpenVPN就有客户端安装教程啦（应该还需要识别一下）</p> {% endcomment %}
    {% comment %} <p>应该再放一个客户端软件在上面（win，mac，安卓），毕竟客户端在国内想下载还挺难的，但是感觉服务器可能承受不了==!，而且流量上来了还可能封IP，保持客户端为最新版也有点麻烦</p> {% endcomment %}
    {% comment %} <p>应该添加一个服务端运行状态的看板，包括软件运行状态，连接终端数量，上一次端口修改时间，端口平均存活时长，端口连通状态等，但是好像有点难，而且目前似乎够用了。</p> {% endcomment %}
    {% comment %} <p>应该做一个用户认证体系，大家都在用同一个证书科学上网，和谁关系不好了拉他进小黑屋还有点麻烦。</p> {% endcomment %}
    
</body>
</html>